roles:
  - unicorn
  - nginx
  - sidekiq

databases:
  production:
    name: play
    username: discourse
    password: password
    host: l.discourse
    host_names:
      - dev1.discourse.org

env:
  DEVELOPER_EMAIL: 'sam.saffron@gmail.com'
  DISCOURSE_HOSTNAME: 'dev.samsaffron.com'
  REDIS_PROVIDER_URL: 'redis://l.discourse:6379'
  RAILS_ENV: 'production'
  RAILS4: 1

version: latest


